apiVersion: kubermatic.k8s.io/v1
kind: Addon
metadata:
  name: kubeflow
  namespace: <NAMESPACE>
  ownerReferences:
  - apiVersion: kubermatic.k8s.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: <CLUSTER_NAME>
    uid: <CLUSTER_UID>
spec:
  cluster:
    kind: Cluster
    name: <CLUSTER_NAME>
    uid: <CLUSTER_UID>
  name: kubeflow
  variables:
    ExposeLoadBalancer: true
    EnableTLS: true
    DomainName: kubeflow.mydomain.io
    OIDCProviderURL: https://dev.kubermatic.io/dex
    OIDCSecret: NQh4P9fIDlEyI6EMKW66TLKLdcIStT4C02
