# Copyright 2021 The Flowmatic Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kubermatic.k8s.io/v1
kind: Addon
metadata:
  name: kubeflow
  namespace: <NAMESPACE>
  ownerReferences:
  - apiVersion: kubermatic.k8s.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: <CLUSTER_NAME>
    uid: <CLUSTER_UID>
spec:
  cluster:
    kind: Cluster
    name: <CLUSTER_NAME>
    uid: <CLUSTER_UID>
  name: kubeflow
  variables:
    ExposeLoadBalancer: true
    EnableTLS: true
    DomainName: kubeflow.mydomain.io
    OIDCProviderURL: https://dev.kubermatic.io/dex
    OIDCSecret: NQh4P9fIDlEyI6EMKW66TLKLdcIStT4C02
