# Copyright 2021 The Flowmatic Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: kubeflow-kubermatic
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/application/v3
    name: application
  - kustomizeConfig:
      parameters:
      - name: serviceType
        value: LoadBalancer
      repoRef:
        name: manifests
        path: manifests/istio/istio-1-3-1-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/stacks/kubernetes/application/cluster-local-gateway-1-3-1
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/istio/istio/base
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/stacks/kubernetes/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/stacks/kubernetes/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/stacks/kubernetes/application/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      parameters:
        - name: oidc_provider
          value: http://dex.auth.svc.cluster.local:5556/dex
        - name: oidc_redirect_uri
          value: /login/oidc
        - name: oidc_auth_url
          value: /dex/auth
        - name: application_secret
          value: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
      repoRef:
        name: manifests
        path: manifests/oidc-authservice
    name: oidc-authservice
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/stacks/kubernetes/application/dex-auth
    name: dex
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/admission-webhook/bootstrap/overlays/application
    name: bootstrap
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/spark/spark-operator/overlays/application
    name: spark-operator
  - kustomizeConfig:
      parameters:
        - name: admin
          value: admin@kubeflow.org
      repoRef:
        name: manifests
        path: manifests/stacks/kubernetes
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: manifests/kubeflow-manifests/kfserving/installs/generic
    name: kfserving
  repos:
  - name: manifests
    uri: github.com/kubermatic/flowmatic?ref=master
  version: v1.2-branch
